"""empty message

Revision ID: 114eaa701872
Revises: c5a5318b6ddb
Create Date: 2023-10-02 16:02:36.097756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '114eaa701872'
down_revision = 'c5a5318b6ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.drop_column('genres')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('artists', schema=None) as batch_op:
        batch_op.add_column(sa.Column('genres', sa.VARCHAR(length=120), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
