"""empty message

Revision ID: 338c191abf4a
Revises: c78e9ae04d66
Create Date: 2023-10-02 18:06:13.808926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338c191abf4a'
down_revision = 'c78e9ae04d66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.drop_column('venues_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('venues', schema=None) as batch_op:
        batch_op.add_column(sa.Column('venues_id', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
