"""empty message

Revision ID: b6e84f6ea85f
Revises: 338c191abf4a
Create Date: 2023-10-03 15:23:00.792978

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b6e84f6ea85f'
down_revision = '338c191abf4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.drop_constraint('shows_artist_image_link_fkey', type_='foreignkey')
        batch_op.drop_constraint('shows_venue_name_fkey', type_='foreignkey')
        batch_op.drop_constraint('shows_artist_name_fkey', type_='foreignkey')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shows', schema=None) as batch_op:
        batch_op.create_foreign_key('shows_artist_name_fkey', 'artists', ['artist_name'], ['name'])
        batch_op.create_foreign_key('shows_venue_name_fkey', 'venues', ['venue_name'], ['name'])
        batch_op.create_foreign_key('shows_artist_image_link_fkey', 'artists', ['artist_image_link'], ['image_link'])

    # ### end Alembic commands ###
